export PATH="$PATH:/usr/local/bin"
export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

export HISTFILE=~/.zhistory
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR='mate -w'
export GIT_EDITOR='nano'

case `uname` in
  Darwin)
    export ZPLUG_HOME="/usr/local/opt/zplug"
    export RBENV_ROOT="/usr/local/var/rbenv"
  ;;
  Linux)
    export RBENV_ROOT="$HOME/.rbenv"
    export PATH="$HOME/.rbenv/bin:$PATH"
    export ZPLUG_HOME="$HOME/.zplug"
  ;;
  FreeBSD)
    # commands for FreeBSD go here
  ;;
esac

###
# Plugins
###

source $ZPLUG_HOME/init.zsh

zplug "modules/prompt", from:prezto
zplug "modules/git", from:prezto
zplug "plugins/textmate", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-history-substring-search"

zstyle ':prezto:module:prompt' theme 'powerlevel10k'

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi
# Then, source plugins and add commands to $PATH
zplug load

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

####

if [ -f $RBENV_ROOT/bin/rbenv ]; then
  if which rbenv > /dev/null; then
    eval "$(rbenv init -)";
  fi
fi
alias ls='ls -G'

# Docker aliases
alias dc="docker"
alias dcm="docker-machine"
alias dcc="docker-compose"

alias gst="git status"
eval "$(hub alias -s)"

alias nreadme="nano README.md"
alias nzshrc="nano $HOME/.zshrc"
alias szsh="source $HOME/.zshrc"

alias ccat='pygmentize -g -O style=colorful'
alias tmux="TERM=screen-256color tmux"

alias be="bundle exec"
alias rst="bundle exec ruby -I'lib:test'"

alias mux="tmuxinator"
alias clear='clear && printf "\e[3J"';
alias lift="open -a ForkLift";

readme () {
  mdless $(ls | grep -i readme)
}

# from http://blog.metamatt.com/blog/2013/01/09/previewing-markdown-files-from-the-terminal/
mdless () {
  pandoc -s -f markdown -t man "$*" | groff -T utf8 -man | less;
}
